--
--local science_multiplier = settings.startup["science-multiplier"].value or 1
--if type(science_multiplier) ~= "number" or science_multiplier <= 1 then
--  log("Science multiplier <= 1 -> skipping data-updates tech scaling")
--  return
--end
--
--log("data-updates: applying science multiplier (formulas & ingredients): " .. tostring(science_multiplier))
--
--for tech_name, tech in pairs(data.raw.technology) do
--  if tech.unit then
--    -- 1) Если формула — обернём и умножим (без грабли с заменой цифр)
--    if tech.unit.count_formula and type(tech.unit.count_formula) == "string" then
--      local old_formula = tech.unit.count_formula
--      tech.unit.count_formula = "(" .. old_formula .. ")*" .. tostring(science_multiplier)
--      log("data-updates: wrapped count_formula for " .. tech_name .. " -> " .. tech.unit.count_formula)
--    end
--
--    -- 2) Масштабируем ингредиенты (science-packs) — корректно для разных форматов
--    if tech.unit.ingredients and type(tech.unit.ingredients) == "table" then
--      for idx, ing in ipairs(tech.unit.ingredients) do
--        if type(ing) == "table" then
--          if type(ing[1]) == "string" and type(ing[2]) == "number" then
--            local old = ing[2]
--            ing[2] = math.max(1, math.floor(old * science_multiplier))
--            log("data-updates: scaled science ingredient for " .. tech_name .. ": " .. ing[1] .. " " .. old .. " -> " .. ing[2])
--          elseif ing.name and (ing.amount or ing.count) then
--            local field = ing.amount and "amount" or "count"
--            local old = tonumber(ing[field]) or 1
--            ing[field] = math.max(1, math.floor(old * science_multiplier))
--            log("data-updates: scaled science ingredient (named) for " .. tech_name .. ": " .. tostring(ing.name) .. " " .. old .. " -> " .. tostring(ing[field]))
--          end
--        end
--      end
--    end
--  end
--end